'use client';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { useAdminQueue } from '@/components/admin/useAdminQueue';
import { QueueFeedback, QueuePager } from '@/components/admin/QueueFeedback';
import { ConfirmAction } from '@/components/account/ConfirmAction';
import { apiFetch } from '@/lib/api/client';
interface Subscriber{id:string;email:string;isActive:boolean;source:string;subscribedAt:string;unsubscribeVersion:number}
export default function NewsletterPage(){
  const [page,setPage]=useState(1),[status,setStatus]=useState('active'),[input,setInput]=useState(''),[search,setSearch]=useState(''),[selected,setSelected]=useState<Subscriber|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const queue=useAdminQueue<Subscriber>(`/api/admin/newsletter?page=${page}&search=${encodeURIComponent(search)}${status?`&status=${status}`:''}`,'subscribers');
  async function deactivate(){if(!selected||busy)return;setBusy(true);setError('');try{const response=await apiFetch('/api/admin/newsletter',{method:'PATCH',body:JSON.stringify({id:selected.id,version:selected.unsubscribeVersion})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to update subscriber');setSelected(null);queue.reload();}catch(failure){setError(failure instanceof Error?failure.message:'Please try again');}finally{setBusy(false);}}
  return <div className="space-y-6"><h1 className="text-3xl font-semibold">Newsletter subscribers</h1><p className="max-w-2xl text-sm leading-7 text-muted-foreground">Manage saved subscriptions. Customers can unsubscribe from their welcome email. Reactivation requires a new customer signup.</p><form className="flex flex-wrap gap-3" onSubmit={event=>{event.preventDefault();setPage(1);setSearch(input);}}><label className="text-sm">Email search<input type="search" value={input} maxLength={100} onChange={event=>setInput(event.target.value)} className="ml-3 min-h-11 rounded-lg border bg-background px-3"/></label><label className="text-sm">Status<select value={status} onChange={event=>{setPage(1);setStatus(event.target.value);}} className="ml-3 min-h-11 rounded-lg border bg-background px-3"><option value="">All</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label><Button type="submit">Search</Button><Button type="button" variant="outline" disabled={queue.loading} onClick={queue.reload}>Refresh</Button></form><QueueFeedback loading={queue.loading} error={queue.error} retry={queue.reload}/>{!queue.loading&&!queue.error&&<><p className="text-sm text-muted-foreground" role="status">{queue.total} subscribers in this view</p><ul className="divide-y rounded-xl border bg-background">{queue.items.map(row=><li key={row.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div className="min-w-0"><p className="break-all font-medium">{row.email}</p><p className="mt-2 text-sm text-muted-foreground">{row.isActive?'Active':'Inactive'} · {row.source} · {new Date(row.subscribedAt).toLocaleDateString('en-LK',{timeZone:'Asia/Colombo'})}</p></div>{row.isActive&&<Button variant="outline" onClick={()=>{setError('');setSelected(row);}}>Unsubscribe</Button>}</li>)}</ul>{!queue.items.length&&<p className="py-6 text-muted-foreground">No subscribers in this view.</p>}<QueuePager page={page} pages={queue.pages} change={setPage}/></>}<ConfirmAction open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}} title="Unsubscribe this address?" description={selected?.email||''} label="Unsubscribe" busy={busy} error={error} onConfirm={()=>void deactivate()}/></div>;
}
