"""Outline FreshPick's wordmark from licensed Acme, without a runtime font.

Usage: python scripts/generate-brand-wordmark.py /path/to/Acme-Regular.ttf
Design tool only: requires fonttools. See public/brand/CREDITS.md.
"""
import json
import math
import sys
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
font = TTFont(sys.argv[1])
glyphs = font.getGlyphSet()
cmap = font.getBestCmap()
scale = 88 / font['head'].unitsPerEm
fresh = []
pick = []
x = 27.0
baseline = 88.0
angles = [-2.0, 0.8, -1.0, 0.8, -0.6, 0.8, -1.0, 0.8, -0.7]
offsets = [0, 0, 0.5, 0, -0.2, 0.5, -0.2, 0, 0.3]

def number(value):
    return format(value, '.2f').rstrip('0').rstrip('.') if value else '0'

def outline(char, at_x, at_y, angle=0):
    pen = SVGPathPen(glyphs, ntos=number)
    radians = math.radians(angle)
    a, b = scale * math.cos(radians), scale * math.sin(radians)
    glyphs[cmap[ord(char)]].draw(TransformPen(pen, (a, b, b, -a, at_x, at_y)))
    return pen.getCommands()

for index, char in enumerate('freshpick'):
    (fresh if index < 5 else pick).append(outline(char, x, baseline + offsets[index], angles[index]))
    x += font['hmtx'].metrics[cmap[ord(char)]][0] * scale - 1.8

leaf = 'M23 73C10 73 3 66 2 54C17 55 25 62 23 73ZM20 71C15 65 10 62 6 59'
width, height = round(x + 6), 113
paths = [dict(color='#61B547', d=leaf + ''.join(fresh)), dict(color='#F4971A', d=''.join(pick))]
svg_paths = ''.join(f'<path fill="{p["color"]}" d="{p["d"]}"/>' for p in paths)
svg = f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}" role="img" aria-label="FreshPick">{svg_paths}</svg>\n'
(ROOT / 'public/brand/freshpick-wordmark.svg').write_text(svg)
data = {'viewBox': f'0 0 {width} {height}', 'width': width, 'height': height, 'paths': paths}
(ROOT / 'components/brand/wordmark-artwork.ts').write_text('// Generated by scripts/generate-brand-wordmark.py; do not hand-edit outlines.\nexport const wordmarkArtwork = ' + json.dumps(data, indent=2) + ' as const;\n')

# Compact f/p mark uses the same letter outlines, safe inside a maskable circle.
mark = f'<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512"><rect width="512" height="512" rx="104" fill="#102E1E"/><g transform="translate(80 38) scale(3.3)"><path fill="#61B547" d="{leaf}{outline("f", 30, 91)}"/><path fill="#F4971A" d="{outline("p", 69, 91)}"/></g></svg>\n'
(ROOT / 'public/brand/freshpick-mark.svg').write_text(mark)
print(f'Wordmark: {width} × {height}; artwork and compact mark generated.')
